### ISSUE TITLE
Safe erase is not honoured by rewiter.erase_op

### ISSUE THREAD

**Issue by 1rre** [xdslproject/xdsl#1128]
See here - `safe_erase` is not passed to `self.erase_matched_op()` on line 157

https://github.com/xdslproject/xdsl/blob/4a62f6cb1a3ea953c32484615bfba175019bd52a/xdsl/pattern_rewriter.py#L149-L163

This can lead to issues eg. by making the following impossible to erase:
`%4 = "flow2.binop"(%3, %4) {"uid" = "sum", "op" = "+"} : (!flow2.node, !flow2.node) -> !flow2.node`

**Comment by kingiler** [comment]
@1rre would you mind providing a minimal working example showing the issue. It is quite hard to see how the issue is triggered.
