### ISSUE TITLE
Circular dependency between different classes through trait usage

### ISSUE THREAD

**Issue by compor** [xdslproject/xdsl#1218]
Currently, a circular dependency between operations via the use of traits cannot be resolved.
Example using `HasParent` and `SingleBlockImplicitTerminator` traits:

```python
@irdl_op_definition
class FooTerminatorOp(IRDLOperation):
    name = "test.foo_terminator"

    # circular reference
    traits = frozenset([HasParent(FooOp), IsTerminator()])


@irdl_op_definition
class FooOp(IRDLOperation):
    name = "test.foo"
 
    # circular reference
    traits = frozenset([SingleBlockImplicitTerminator(FooOp)])
```

**Comment by math-fehr** [comment]
Just as a note, this is very related to #12, which is about circular dependencies in operands/results.
I may try to look into it soon!

**Comment by compor** [comment]
@math-fehr I didn't mean to create issue bloat. I can move this description to that issue and close this one if you want.

**Comment by superlopuh** [comment]
I would vote for keeping both issues separate.
