### ISSUE TITLE
Implicitbuilder does not check if block arguments are used for declared types

### ISSUE THREAD

**Issue by JosseVanDelm** [xdslproject/xdsl#1303]
Hi,

I was using the following code:
```python
...
is_positive_block = Block(arg_types=(i32,))
with ImplicitBuilder(is_positive_block):
     scf.Yield.get(integer)
absolute_value = scf.If.get(is_negative,
                       [i32],
                       [is_negative_block],
                       [is_positive_block])
...
```
Which gives this somewhat weird MLIR code
```mlir
%9 = "scf.if"(%4) ({
      ...
      }, {
      ^4(%13 : i32):
        "scf.yield"(%2) : (i32) -> ()
      }) : (i1) -> i32
```
In which `%13` is never used.
This is because I don't use the `as` in:
```python
is_positive_block = Block(arg_types=(i32,))
with ImplicitBuilder(is_positive_block) as (my_variable,):
```
While there's no guarantee that `my_variable` will actually be used further down in python code even if I use the `as`, it seems like ImplicitBuilder could at least check if it is not present in the python code, because it can never be assigned if the `as` statement is not there in the first place?

**Comment by superlopuh** [comment]
Just to make sure I understand correctly, this is a feature request to raise some sort of error if a block argument is not used in the Python code?

**Comment by JosseVanDelm** [comment]
Hi @superlopuh,

I'm sorry but I'm going to close this, as I've just found a case in which you would actually need this behaviour and an error would make it impossible to write the code:
i.e. _a for loop where the induction variable is not accessed inside the region needs a type to be declared, even if the induction variable is not used within th efor loop region._
```mlir
      "scf.for"(%3, %15, %12) ({
      ^^^^^^^^^----------------------------------------------------------------------------------------------------------------------------------------------------------
      | Operation does not verify: Wrong number of block arguments, expected 1, got 0. The body must have the induction variable and loop-carried variables as arguments.
      -------------------------------------------------------------------------------------------------------------------------------------------------------------------
        %16 = "arith.subi"(%15, %12) : (i32, i32) -> i32
        %17 = "arith.subi"(%16, %16) : (i32, i32) -> i32
```
Guess this was just my misunderstanding again.
I should've opened a thread on this on zulip before "complaining"! I'm sorry!

**Comment by superlopuh** [comment]
No, thank you for the issue, these things tend to be much easier to find using GitHub search than zulip search, so I think this was a useful thread.
