### ISSUE TITLE
Improve indentation of regions when printing ASTs

### ISSUE THREAD

**Issue by tobiasgrosser** [xdslproject/xdsl#14]

**Comment by Dinistro** [comment]
Is this issue resolved or do you have a plan for even more improvements?

**Comment by tobiasgrosser** [comment]
Thank you for checking in. This is resolved as soon as @math-fehr releases xdsl 0.0.9 and we update this repo to xdsl 0.0.9. This update will require some minor test case adjustments.

**Comment by tobiasgrosser** [comment]
Indeed, this is resolved.
