### ISSUE TITLE
Dependency is not installed.

### ISSUE THREAD

**Issue by K-W-Li** [xdslproject/xdsl#151]
```
pip install xdsl
```
then run
```
python -c "from xdsl.ir import *"
```
will throw
```
ModuleNotFoundError: No module named 'frozenlist'
```

It means the dependencies of xDSL like ```fronzenlist``` is not installed. Most likely the package does not have proper indication of its dependency.

**Comment by tobiasgrosser** [comment]
That is interesting. requirements.txt lists:

`yapf<0.33.*
pytest<7.2.*
filecheck<0.0.23
lit<15.0.*
frozenlist<1.4.*
toml
``

Any idea what could go wrong?
```

**Comment by georgebisbas** [comment]
I think it was never expected to work this way.
No one has actually worked on delivering pip packaging so far, but was mostly to acquire the xdsl name.
Right?
I can put some effort on this.

**Comment by tobiasgrosser** [comment]
Right. That would be super helpful.

**Comment by georgebisbas** [comment]
@K-W-Li could you check if this is fixed for you now?

**Comment by K-W-Li** [comment]
@georgebisbas pip install still installs 0.5.3 which hasn't fix the bug.
Maybe need to update pypi repo?
