### ISSUE TITLE
Typo in Readme for installation of optional dependencies

### ISSUE THREAD

**Issue by martin-luecke** [xdslproject/xdsl#158]
The README states: 
`pip install -r requirements-optionals.txt`

However, the file on the toplevel is called `requirements-optionals.txt`, i.e. without the 's'

**Comment by tobiasgrosser** [comment]
This seems to be a bug. They should be called identical, e.g. `requirements-optional.txt`. Would you mind submitting a PR?

**Comment by math-fehr** [comment]
Thanks, I just fixed this
