### ISSUE TITLE
Parsing error when parsing an op without attributes and then another with multiple results

### ISSUE THREAD

**Issue by martin-luecke** [xdslproject/xdsl#171]
Example:
```C++
some.op() []
(%val : !i32, %other_val : !i32 = some.other_op()
```
When the "[]" are removed the parser fails.

[here](https://github.com/xdslproject/xdsl/blob/2c2d23d195e7c38a25b8fb4fcb856900eabe3af2/tests/composable_rewriting/strategies.xdsl#L54) is an example in the code base. 
It fails with:
```
xdsl.parser.ParserError: Parsing error at 55:6:
    (%op : !operation, %op_res : !value) = match.root_op(%int_type : !type<!i32>) []
     ^
')' expected
```

The parser has not returned from parsing the previous op and tries parsing the results of the second op as successors of the first op.

**Comment by math-fehr** [comment]
Fixed as we removed the xDSL format
