### ISSUE TITLE
Fix DenseIntOrFPElementsAttr constructor

### ISSUE THREAD

**Issue by math-fehr** [xdslproject/xdsl#179]
If given integer values, but a float type, to `tensor_from_list` of `DenseIntOrFPElementsAttr`, the values won't be converted to float values.

**Comment by meshtag** [comment]
I am interested in working on this issue. 

From what I understand, I think the following is a minimum example to demonstrate the addressed behaviour (please correct me if I am wrong) : 

```
from xdsl import *
from xdsl.ir import *
from xdsl.irdl import *
from xdsl.dialects.arith import *
from xdsl.dialects.builtin import *
from xdsl.parser import *
from xdsl.printer import *
from xdsl.util import *

# Printer used to pretty-print MLIR data structures
printer = Printer()

checkAttr = DenseIntOrFPElementsAttr.tensor_from_list([4, 5], f32)

printer.print_attribute(checkAttr)
print()
```

Obtained error is : 
```
raise VerifyException(
xdsl.irdl.VerifyException: array data expects attribute list, but 0 element is of type <class 'int'>
```

I think we can solve this by performing typecasting (either implicit or explicit) at [this](https://github.com/xdslproject/xdsl/blob/c5e0d11cf51eeaeb09aa1167b149224303bc0231/xdsl/dialects/builtin.py#L583) location. 
Ex. 
```
data_attr = [
            FloatAttr.from_value(float(d), type.element_type)
            if isinstance(d, float) else d for d in data
        ]
```

Please let me know if I am on the right track and I'll be happy to create a PR to fix this.

**Comment by meshtag** [comment]
Gentle ping @math-fehr

**Comment by math-fehr** [comment]
Sorry, I completely missed this!
Yes, a PR would be greatly appreciated for this ;)
I think the typecasting at this place is the right approach.
Also, note that in the case where the argument is a float attribute, we do not want to cast it back!

Thanks a lot!

**Comment by meshtag** [comment]
Thanks for your response!

Can the same problem be extrapolated to cases involving the construction of `DenseIntOrFPElementsAttr` with float values given and the type specified as an integer or index. (Ex. `i32`, `i16`)?

Following is an example of above scenario : 
```
checkAttr = DenseIntOrFPElementsAttr.tensor_from_list([4.0, 5.0], i32)
```
Obtained exception is : 
```
raise VerifyException(
xdsl.irdl.VerifyException: array data expects attribute list, but 0 element is of type <class 'float'>
```

**Comment by math-fehr** [comment]
I am not sure that we would like this for floating points actually!

One problem is that ˋint(x)ˋ might raise an exception (for instance if x is inf or NaN).

Also, while transforming an integer to float makes sense, doing it from a float to an integer feels a bit weird to me.
