### ISSUE TITLE
add filecheck test for add.onnx

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#1898]
Might as well just copy the example from the onnx-mlir repo

https://github.com/onnx/onnx-mlir
https://github.com/onnx/onnx-mlir/tree/main/docs/doc_example
https://github.com/onnx/onnx-mlir/blob/main/docs/doc_example/gen_add_onnx.py

**Comment by superlopuh** [comment]
This file should probably live in the `tests/filecheck/projects/onnx` directory, now that I think about it

**Comment by brnorris03** [comment]
Is the intent to check just syntax, and if so, is this sufficient? https://github.com/xdslproject/xdsl/tree/boyana/onnx-add/tests/filecheck/dialects/onnx

**Comment by superlopuh** [comment]
I meant to parse a .onnx file and output IR with the onnx dialect

**Comment by superlopuh** [comment]
So this will require adding the onnx frontend to xdsl-opt

**Comment by tobiasgrosser** [comment]
I would suggest to add the onyx dialect without full front end support. We do not need an end to end compiler to test onyx.

**Comment by superlopuh** [comment]
What's the downside of having it?

**Comment by superlopuh** [comment]
Just to clarify, I don't think we need this for any of the onnx-to-linalg work, it's more to keep track of useful links for the onnx format support if/when we decide to add it
