### ISSUE TITLE
Capture BlockArg changes in RewriteAction 

### ISSUE THREAD

**Issue by Dinistro** [xdslproject/xdsl#21]
Currently, the walker simply duplicates the `BlockArguments` of Blocks it traverses, independent of any changes a pattern might have caused. When a pattern modifies the arguments the pattern does not notice and thus does not bookkeep them. 

I guess one could somehow integrate this into the RewriteAction, but it might be costly to detect these changes. On the other hand, informing the RewriteAction manually about every change might be cumbersome and error-prone. 

Note: This might be solvable by introducing some kind of Rewriter, as MLIR has it, which either replaces or changes operations. The MLIR rewriter must be used to perform any modification on the IR, which in turns allows to introduce arbitrary hooks from the framework side, as all actions will go through it.

**Comment by Dinistro** [comment]
In my current use case, this is even more complicated: 
```
choco.ir.func_def() ["func_name" = "Sum", "return_type" = !choco.ir.named_type<"int">]{
  ^0(%p : !choco.ir.memloc<!choco.ir.named_type<"int">>): 
  ...
```

has to be replaced by something as follows

```
builtin.func() ["sym_name" = "Sum", "type" = !fun<[!i32], [!i32]>, "sym_visibility" = "private"]{
  ^0(%p_val : !i32):
     %p_new : !memref<[1 : !i64], !i32> = memref.alloca() [...]
     memref.store(%p_val : !i32, %p_new : !memref<[1 : !i64], !i32>)
     
     // replace all usages of %p with %p_ref in all other operations
}
```

I'll probably implement this a more complicated rewrite that does not really on the xdsl tooling for now.

**Comment by math-fehr** [comment]
So I don't think we could have something like this in the current version of the walker, so we should probably create a new kind of rewriter/walker for this.
Maybe I could try to write something similar to what MLIR uses a queue, and requires the use of a `Rewriter` for any transformation?

**Comment by Dinistro** [comment]
I guess this would be helpful. I'm not yet sure about the interface of it, i.e., what rewrite operations is should support. 
Defining how one modifies a region of the old operation and reuses it iin a new operation might be a bit hard to do.

**Comment by Dinistro** [comment]
Should we maybe discuss this to figure out what we do actually require here? I fear that this might be non-trivial to implement, so being on the same page might be useful.

**Comment by Dinistro** [comment]
This was fixed by the introduction of the rewrite engine.
