### ISSUE TITLE
interpreter: (riscv) external function call in riscv_func does not handle register dictionary in RiscvFunctions

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#2122]
When calling an external function call, there is currently an error of a0 not being set.

**Comment by compor** [comment]
what's the minimal reproduction example? is there a filecheck?
I'd like to tackle how we explicitly use registers for func arguments, so this might be related eventually.

**Comment by superlopuh** [comment]
This is super low priority, it's just the interpreter, I'm not actually sure where the problem is, but it's easy to reproduce in the branch that references this issue

**Comment by compor** [comment]
Yeah, no worries, I'm just doing some issue janitorial work.
