### ISSUE TITLE
Yapf prevent CI checks

### ISSUE THREAD

**Issue by math-fehr** [xdslproject/xdsl#236]
We should try to change the CI such that wrong formatting does not skip the other steps of the CI, such as testing.

**Comment by webmiche** [comment]
I don't think it does. We have four jobs atm:
- yapf
- testing
- jupyter 3.10
- jupyter 3.11

Looking at #230 you can see that `CI - Python application / build (3.10) (pull_request) ` passed. This is testing. What we should however do is give this CI job a proper name, s.t. one actually knows that it does.

**Comment by georgebisbas** [comment]
I agree with @webmiche , how did you see this @math-fehr ?
