### ISSUE TITLE
dialects: (x86) move assembly helpers to assembly.py

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#2377]
We'd like to keep `ops.py` dedicated to the ops in the dialect

**Comment by KGrykiel** [comment]
Hi, just about ready to look into that, is the idea to make the assembly.py file for x86 specifically or also to extract the common functionality from both x86 and riscv and put it into xdsl/backend?

**Comment by superlopuh** [comment]
I think x86 is the priority, but factoring out common functionality to the two of them could also be nice, and make it slightly easier to add ARM in the future
