### ISSUE TITLE
Declarative format doesn‘t seem to support parsing declared integer types

### ISSUE THREAD

**Issue by lucjaulmes** [xdslproject/xdsl#2449]
When declaring an integer attribute to be a certain type (here, and 8-bit signless int), and using declarative assembly format, the automatically parsed value is incorrectly inferred to be `i64` (should be `i8` in this case).

I’ve pushed the code that reproduces lucjaulmes/xdsl@3bd17400a309b9dd8413c2c0cded266265e54e19

For the sake of discussion, I copy here the operation definition:
```py
@irdl_op_definition
class ClockDivider(IRDLOperation):
    """Produces a clock divided by a power of two"""

    name = "seq.clock_div"

    pow2 = attr_def(IntegerAttr[Annotated[IntegerType, IntegerType(8)]])
    input = operand_def(ClockType())
    output = result_def(ClockType())

    […]

    assembly_format = "$input `by` $pow2 attr-dict"
```

Test code:
```mlir
%div_clk = seq.clock_div %clk by 4
```

And test error:
```
  %div_clk = "seq.clock_div"(%clk) {"pow2" = 4 : i64} : (!seq.clock) -> !seq.clock
  ^^^^^^^^^^^^^^^^^^^^^^^^^^------------------------------------
  | Operation does not verify: Expected attribute i8 but got i64
  --------------------------------------------------------------
```

Pinging @math-fehr as suggested by @PapyChacal.

**Comment by PapyChacal** [comment]
Implemented in
- #2493
