### ISSUE TITLE
The `onnx` Python module seems to have become a dependency

### ISSUE THREAD

**Issue by Moxinilian** [xdslproject/xdsl#2470]
When running `make tests`, tests seem to fail on my machine as `xdsl/frontend/onnx/ir_builder.py` cannot find things from the onnx module. I do not have it installed on my machine, which makes me suspect it is a newly introduced dependency that has not been added to the requirements. Is that the case?

@alecerio @superlopuh

**Comment by superlopuh** [comment]
I'll have a look
