### ISSUE TITLE
dialects: (llvm) MLIR LLVM dialect NullOp replaced by ZeroOp

### ISSUE THREAD

**Issue by mcjamieson** [xdslproject/xdsl#2523]
The MLIR NullOp has been replaced by ZeroOp (see: https://github.com/llvm/llvm-project/pull/67183). 

This has been highlighted by the HLFIR changes and related upgrade to 'flang-new' v18.

**Comment by mcjamieson** [comment]
We will need to not only update the LLVM dialect but also `lower_mpi.py` transform.

**Comment by PapyChacal** [comment]
I'm curious, can I see a specific error or problem you faced? AFAIU we test this transformation in the DeVito fork's CI and nothing appeared wrong there.
Pinging @AntonLydike and @georgebisbas in case they know something I don't on that point?

**Comment by mcjamieson** [comment]
```
loc("generated/module_1.mlir":3:10): error: LLVM Translation failed for operation: llvm.mlir.null
error: failed to create the LLVM module
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: flang-new -fc1 -emit-obj generated/module_1.mlir
```
builtin.module {
  func.func @_QQmain() {
    %0 = "llvm.mlir.null"() : () -> !llvm.ptr
    %1 = func.call @MPI_Init(%0, %0) : (!llvm.ptr, !llvm.ptr) -> i32
...
