### ISSUE TITLE
xDSL: Verifier for i1 attribute 

### ISSUE THREAD

**Issue by meshtag** [xdslproject/xdsl#270]
No exception is triggered when we try to construct an `i1` attribute from potentially illegal values. 
Ex.  `i1_constant = Constant.from_int_and_width(10, i1)` doesn't result in a `TypeError` 
while `i32_constant = Constant.from_int_and_width(10.2, i32)` results in 
```
raise TypeError(
TypeError: No available IntAttr builders for arguments (10.2,)
```

**Comment by webmiche** [comment]
If we want to check this, it would probably make sense to check this for any IntegerAttr. Basically, I feel that a custom verifier in [IntegerAttr](https://github.com/xdslproject/xdsl/blob/main/xdsl/dialects/builtin.py#L176) checking that the given value fits inside 2^width is the way.

**Comment by math-fehr** [comment]
Yes, we should add a verifier for `IntegerAttr` to check that they are in the right range.
We should also probably add an option that will round the value upon creation.

**Comment by meshtag** [comment]
> Basically, I feel that a custom verifier in [IntegerAttr](https://github.com/xdslproject/xdsl/blob/main/xdsl/dialects/builtin.py#L176) checking that the given value fits inside 2^width is the way.

Something like this? 
```
def verify(self) -> None:
        if (self.value.data < -pow(2, self.typ.width.data - 1) or 
            self.value.data > pow(2, self.typ.width.data - 1) - 1):
            warnings.warn(f"Out of bounds value provided for the given type {self.typ}.")
```

> We should also probably add an option that will round the value upon creation.

Perhaps a static variable in `class IntegerAttr` with default value true for rounding-off?

I think we should also add a similar verifier mechanism for `FloatAttr` as well. I can start working on a PR if we agree that this is the right way to move forward.

**Comment by webmiche** [comment]
Hmm, another thing to consider here is that MLIR integers are singless. I would assume that we take the same decision. This means that verifying their value becomes a bit harder as you don't know what to check exactly.

I would change your verifier to a range of -2^(width-1) to 2^(width), as this contains both ranges for signed and unsigned integers. Therefore, if this verifier actually gets triggered, it is clear that something has gone wrong. Clearly, we then allow some wrong cases which is not very nice...

**Comment by math-fehr** [comment]
From a quick check with MLIR, we should have the following ranges:
* -2^(width - 1) to 2^width for signless integers
* 0 to 2^width for unsigned integers
* -2^(width - 1) to 2^(width -1) -1 for signed integers

We do not have signed/unsigned in xDSL currently, so we should only keep the signless ones, with the ranges Michel suggested.

**Comment by math-fehr** [comment]
I actually don't know what are the semantics for signless is when things are out of bounds :/
Though this is a problem that MLIR has as well
