### ISSUE TITLE
Parsing/Printing: print result type at the end of an operation

### ISSUE THREAD

**Issue by tobiasgrosser** [xdslproject/xdsl#28]
I would prefer to parse the type **after** an assignment to be more in line with what MLIR uses. I also find the delayed type easier to read as the interesting information, the operation that we call, is frontloaded.

Instead of:

```
%0 : !riscv_ssa.reg = riscv_ssa.li() ["immediate" = 42 : !i64]
%1 : !riscv_ssa.reg = riscv_ssa.mul(%0 : !riscv_ssa.reg, %0 : !riscv_ssa.reg)
```

I would expect to read:

```
%0 = riscv_ssa.li() ["immediate" = 42 : !i64] : !riscv_ssa.reg 
%1 = riscv_ssa.mul(%0 : !riscv_ssa.reg, %0 : !riscv_ssa.reg) : !riscv_ssa.reg 
```

**Comment by Dinistro** [comment]
Fixed by the mlir printing style
