### ISSUE TITLE
Try ruff for linting

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#280]
Just found this linter that seems to be much faster than what we're currently using. I'm not sure how easy it would be to integrate with the CI and everyone's dev environments, but seems worth looking into.

https://github.com/charliermarsh/ruff

**Comment by math-fehr** [comment]
Do you know how much linting do they cover? For instance compared to pylint?
It seems quite a lot of people rely on them, so I'm perfectly okay using this!
It would be even better if they have a nice github action for this ;)

**Comment by superlopuh** [comment]
@PapyChacal
