### ISSUE TITLE
Function _parse_builtin_densearray_attr fails when parsing a dense array with element_type IndexType 

### ISSUE THREAD

**Issue by watermelonwolverine** [xdslproject/xdsl#3154]
The function `_parse_builtin_densearray_attr` does not accept dense arrays with element_type `IndexType`. On the other hand, the function `DenseArrayBase.create_dense_int_or_index` does accept `IndexType` as element_type.

**Comment by superlopuh** [comment]
Tagged as "good first issue", I expect resolving this is looking up what MLIR does for this, and making sure that both the functions do the expected thing.
