### ISSUE TITLE
Operand segment sizes value type changed in MLIR

### ISSUE THREAD

**Issue by mesham** [xdslproject/xdsl#326]
Previously operand segment sizes followed _dense<[0, 0]> : vector<2xi32>_ whereas now MLIR has been updated for this to be _array<i32: 0, 0>_ . This is needed for Flang to process the FIR MLIR from our PSyclone generation.

From chatting with Mathieu it's a question of changing to use ArrayAttr from DenseIntOrFPElementsAttr and some updates to the parser and printer.

**Comment by webmiche** [comment]
closed by #327
