### ISSUE TITLE
scf.for implicit terminators

### ISSUE THREAD

**Issue by alexarice** [xdslproject/xdsl#3325]
The implicit terminator infrastructure for `scf.for` does not seem to work correctly at the moment. See #3303

**Comment by compor** [comment]
This is now done, right? I didn't dig deeper but seems the (unrelated) issue that #3303 was trying to solve with printing unregistered ops. If so, close this or please elaborate with a MWE and I'll get around to it.

**Comment by alexarice** [comment]
```
%0 = arith.constant 0 : index
scf.for %iv = %0 to %0 step %0 {
  "unregistered"() : () -> ()
}
```
I would expect this to verify

**Comment by alexarice** [comment]
For comparison this is ok:
```
%0 = arith.constant 0 : index
scf.for %iv = %0 to %0 step %0 {
  "test.op"() : () -> ()
}
```
