### ISSUE TITLE
Make xDSL programs executable thorugh RiscEmu in the browser

### ISSUE THREAD

**Issue by PapyChacal** [xdslproject/xdsl#346]
It would be nice to have a RISC-V backend to run xDSL programs through the RiscEmu emulator. RiscEmu being pure python, it should just run on the web, allowing to run xDSL-compiled programs right in the browser.

**Comment by webmiche** [comment]
Not sure how this relates to the course work of @tobiasgrosser 's course. Isn't lowering to RISC-V part of a project there?

**Comment by PapyChacal** [comment]
It is, this requires some thought indeed.
