### ISSUE TITLE
Make notebooks cells executable out of order

### ISSUE THREAD

**Issue by PapyChacal** [xdslproject/xdsl#347]
Currently, running all cells from a notebook in a fresh kernel is fine, but some notebooks are throwing errors when a cell is executed again. Can we find a way to allow any order execution?

**Comment by georgebisbas** [comment]
Although I understand your worry, this is not supposed to work like this.
NOtebooks have this waterfall type of execution...
Do you have any motivating examples behind this?

**Comment by PapyChacal** [comment]
Not really, we just thought it might give a wrong impression to newcomers to both xDSL and notebooks.

This could probably be solved on the notebook UI level, replacing the 'execute selected cell' command/shortcuts by some 'restart and execute all cell up to the selected one'.
Would that feel wrong for users used to notebooks?

**Comment by superlopuh** [comment]
I think there's a "🔥 this is fine 🔥" approach to notebooks ending up with weird state by people who use them, there's a bunch of projects trying to fix it but everyone who uses them a lot learns to watch out for it, usually. I would say that we should keep it in mind but not be too clever about it.

**Comment by superlopuh** [comment]
NTBF
