### ISSUE TITLE
dialects: (bufferization) MaterializeInDestination wrong operands

### ISSUE THREAD

**Issue by francescodaghero** [xdslproject/xdsl#3489]
https://github.com/xdslproject/xdsl/blob/59e59ad334247498b59e14dc70a481a5957dba59/xdsl/dialects/bufferization.py#L191-L197

The [MaterializeInDestinationOp](https://mlir.llvm.org/docs/Dialects/BufferizationOps/#bufferizationmaterialize_in_destination-bufferizationmaterializeindestinationop) in MLIR allows the dest operand to be of any shaped type (e.g. Tensor or MemRef). It does not seem the case for xDSL, as the current implementation forces TensorType for all operands.

**Comment by alexarice** [comment]
Working on this now but will take a little time as we currently don't have the `functional-type` assembly format directive and it seems necessary to be able to get the custom format correct.
