### ISSUE TITLE
Write frontend and backend specific notebooks

### ISSUE THREAD

**Issue by PapyChacal** [xdslproject/xdsl#351]
Some users will probably be only interested in adding a new frontend or backend to xDSL. It could be interesting to have specific tutorials notebooks for those use cases.

**Comment by superlopuh** [comment]
Let's revisit this issue once the Toy & Kaleidoscope notebooks are ready, we might find that they already cover the frontend & backend work

**Comment by superlopuh** [comment]
I feel like this task is covered by other issues in the project, please let me know if you think it isn't.
