### ISSUE TITLE
misc: add Kaleidoscope chapter 2: AST -> MLIR Builtin dialect

### ISSUE THREAD

**Issue by PapyChacal** [xdslproject/xdsl#352]
It could be interesting to have a calculator tutorial, which could be a simple enough example to show new users how simple it can be to build a full compiler with xDSL.

**Comment by superlopuh** [comment]
I'll reuse this issue to track Kaledoscope work that's not much more complex than a calculator

**Comment by superlopuh** [comment]
I think this content is covered in the Toy tutorials, removing
