### ISSUE TITLE
core: (Parsing) The int value of a BoolAttr that is `true` is `-1` instead of `1`

### ISSUE THREAD

**Issue by watermelonwolverine** [xdslproject/xdsl#3684]
I'm not sure that this is a bug. Reading through the code and the comments it seems to me that true should equal to 1 and false should equal to 0 but this is not the case. During parsing true is initially read as 1 but it is later normalized to -1 by `IntegerType.normalized_value`. 

Might this an issue with normalization of i1 values?

**Comment by superlopuh** [comment]
This is how signed integers work, and should maybe be documented better, but the largest negative number is 1 bigger than the largest positive number in signed integers, meaning if the positive range goes up to 0, the negative range goes down to -1.

**Comment by watermelonwolverine** [comment]
The documentation in https://github.com/xdslproject/xdsl/blob/346e1d4d95a8a2eefc130d0ef1c93c7159b41765/xdsl/parser/base_parser.py#L42 and https://github.com/xdslproject/xdsl/blob/346e1d4d95a8a2eefc130d0ef1c93c7159b41765/xdsl/parser/base_parser.py#L72 need to be fixed.

I would also suggest adding something like
```python
    def to_bool(self) -> bool:
        return bool(self.value.data)
```
to IntegerAttr as a counterpart to `from_bool`. This looks too simple to be useful but I had several bugs in my project after upgrading to 0.25.0 because I worked on the assumption that true always equals 1 and false always equals 0 so I hastily implemented the checks based on that assumption. It's nice not having to make this assumption.
