### ISSUE TITLE
Structural equality refactor

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#393]
The Python approach to equality is to provide two kinds of equality, referential equality (`a is b`) and structural equality (`a` == `b`). In xDSL, the `==` operator is redefined to test for referential equality, and structural equality has a separate function. It would be less surprising to users of the framework if the `Op`s behaved similarly to other python classes w.r.t. equality.

There are two complications to this: one is that the structures hold circular references, making it hard to test for structural equality the naïve way. Another is that equality should be consistent with hashing, and if two objects are the same then their hashes should be the same. We need to solve both problems and test them well to resolve this issue.

**Comment by webmiche** [comment]
IMO, this is a naming issue in some sense. Personally, I am not versed enough in MLIR to really know when people call two operations "equal", and that's what this comes down to for me. I think an API must be intuitive and if I check `==` I want to check whether things are "equal", so whether I would understand those two object as being equal. Clearly, that's not exactly the same thing as being "the same", which is when I would use `is`.

The other thing is that I fear that this decision might have huge runtime impacts. From what I understand, we would need to basically rename the current structural equivalence checks to `__eq__` and that would solve things. But, as you mentioned, we would then also have to compute the hashes in a way that takes into account the hashes of all operands/results/..., which would mean a "simple" hash would have to crawl through the entire datastructure to compute the hash. This sounds extremely wasteful to me. 

Also, notice that the hash of an operation would potentially change when something "unrelated" in the IR would change. Say we take the hash of operands into account, which themselves have operands. That would mean that changing an operation will change the hash of all operations that are contained in its def-use chain and even the ones that are contained in the def-use chain of an operation contained in the def-use chain, so pretty much the transitive closure of the def-use chain.

These are just some thoughts dumbed here. Maybe I am missing something obvious :sweat_smile:

**Comment by superlopuh** [comment]
No, you're right, there are tons of things to look out for. This is a good place to document where the potential pitfalls might be, so that whoever tackles this has a good place to refer to. Potentially setting a breakpoint on the hash function and running the tests in debug might be a good idea.

**Comment by webmiche** [comment]
I must also admit that I am not quite sure how important the runtime of the hash actually is. I don't actually know which parts of Python really on it, though i feel that I heard that some comparisons in the context of dictionaries use it. Not sure how that exactly that translates to the performance of our entire framework...

**Comment by superlopuh** [comment]
My intuition is that it wouldn't be noticeable, but you never know until you measure

**Comment by superlopuh** [comment]
I no longer think this is worth doing, closing
