### ISSUE TITLE
Add support for signed integers

### ISSUE THREAD

**Issue by Dinistro** [xdslproject/xdsl#42]
Currently builtin's IntegerType has no signedness information, thus all integers are treated as unsigned integers, which is a limitation for our lowering to mlir.

**Comment by webmiche** [comment]
It even is the case that int<-1> crashes the parser.

**Comment by Dinistro** [comment]
Note that `i32` and `ui32` are not the same thing. To be consistent with MLIR we should stick with `i32` and use explicit signed operations on these integers. The only thing left is to support proper parsing of negative integer literals.

**Comment by Dinistro** [comment]
fixed in #84
