### ISSUE TITLE
Implicit attribute constraint instanciation is confusing

### ISSUE THREAD

**Issue by Moxinilian** [xdslproject/xdsl#424]
In situations where a constraint is expected, sometimes attributes get implicitly coerced into an `EqAttrConstraint`, which allows you to write definitions like

```py
@irdl_op_definition
class FooBar(Operation):
    name = "foo.bar"
    baz: OpAttr[IntegerAttr]
```

However, if not familiar with the constraint system, one would expect the following to work as well:

```py
@irdl_op_definition
class FooBar(Operation):
    name = "foo.bar"
    baz: OpAttr[AnyAttr]
```

but it does not, because `AnyAttr` is a constraint that one must instantiate.

I do not really know what the best thing to do about this is. There are a few easy ideas, though:

- Do nothing. Maybe with better documentation it will become obvious `AnyAttr` is not the same construct as say `IntegerAttr`.
- Detect classes that derive from Constraint and instantiate them automatically. That is kind of gross but would lead to the desired effect.
- Require `EqAttrConstraint` to be created explicitly. This would probably be very boilerplatey.

**Comment by math-fehr** [comment]
Yep, this is broken, I think we should do is:
* throw an error when given a constraint in the type part (you should use annotated), or when given a class that is not an attribute (I thought we would already give an error on that though?)
* Rename AnyAttr to AnyConstraint

What do you think?

**Comment by Moxinilian** [comment]
Yeah I think your first point is already in place. Your second solution would definitely help I think. Great idea.

**Comment by superlopuh** [comment]
I thikn `AnyAttrConstraint` is marginally nicer, although we could also special-case it in the irdl magic. It also feels like it could be called `_AnyAttrConstraint`, and that the official preferred way of spelling this could be `OpAttr[Any]` or `OpAttr[Attribute]`

**Comment by math-fehr** [comment]
Yes, the current preffered way is `OpAttr[Attribute]`, since it provides better typing. `AnyAttrConstraint` should be only very rarely used.

**Comment by superlopuh** [comment]
We no longer use this API, support both `AnyAttr()` and `Attribute` in the equivalent case, and `Pyright` gives a hopefully useful error when `AnyAttr` the class name is used.
