### ISSUE TITLE
Incorrectly constructed diagnostic

### ISSUE THREAD

**Issue by Moxinilian** [xdslproject/xdsl#425]
When parsing
```mlir
    "pdl_interp.is_not_null"(%0)[^bb2, ^bb1] : (!pdl.operation) -> ()
```
in MLIR mode, with the following definitions:
```py
@irdl_attr_definition
class OperationType(ParametrizedAttribute):
    name = "pdl.operation"
```
and
```py
@irdl_op_definition
class PdlInterpIsNotNull(Operation):
    name = "pdl_interp.is_not_null"
    value: Operand
```

I get a very weird error message that looks a lot like a type error bug in xDSL:
```
xdsl.utils.exceptions.ParseError: test_pdl.mlir:6:68
    "pdl_interp.is_not_null"(%0)[^bb2, ^bb1] : (!pdl.operation) -> ()
                                                                    ^
                                                                    Unexpected exception: '^bb2'
```

Am I defining successors in `PdlInterpIsNotNull` incorrectly? In any case, that does look like an intended error message.

**Comment by Moxinilian** [comment]
I believe the bug is something related to the parser trying to fetch a block, but failing because said block has not been parsed yet.

**Comment by math-fehr** [comment]
Oh yes, it seems that this is exactly the problem.

**Comment by Moxinilian** [comment]
Correct me if I am wrong but I don’t believe this is fixed.
