### ISSUE TITLE
xDSL: Encode generic verifiers as part of the annotation 

### ISSUE THREAD

**Issue by meshtag** [xdslproject/xdsl#426]
We can potentially encode some generic/recurring verifiers as part of the annotation itself while accepting an operation operand. This would make things more declarative and potentially eliminate repetitive code imo. 

Some examples to demonstrate this are 
 -  [`VectorOfRankAndType`](https://github.com/llvm/llvm-project/blob/8d92a8226eb71f0199f4cc83b961bf5440a1e503/mlir/include/mlir/Dialect/Vector/IR/VectorOps.td#L1766) instead of [this](https://github.com/xdslproject/xdsl/blob/c125842305913232b25aa81f6c3abcfe2cc44691/xdsl/dialects/vector.py#L195)
 - [`VectorOfRank`](https://github.com/llvm/llvm-project/blob/8d92a8226eb71f0199f4cc83b961bf5440a1e503/mlir/include/mlir/Dialect/Vector/IR/VectorOps.td#L1767) instead of [this](https://github.com/xdslproject/xdsl/blob/c125842305913232b25aa81f6c3abcfe2cc44691/xdsl/dialects/vector.py#L192)

**Comment by math-fehr** [comment]
This has been added since
