### ISSUE TITLE
tests: Filecheck is not accurate with exact string to string matching

### ISSUE THREAD

**Issue by meshtag** [xdslproject/xdsl#428]
The `Filecheck` python package does not accurately compare the obtained `IR` and expected `IR`. Although it is capable of detecting major differences, it fails to report small changes. 

Example: [This line](https://github.com/xdslproject/xdsl/blob/93f2ae6cd47ba0c3f2d1a6f19ca0885423d8d528/tests/filecheck/dialects/vector/vector_ops.xdsl#L21) should ideally receive the `i1 vector` as an argument, since it was present in the [initial version](https://github.com/xdslproject/xdsl/blob/93f2ae6cd47ba0c3f2d1a6f19ca0885423d8d528/tests/filecheck/dialects/vector/vector_ops.xdsl#L6) ([Ref](https://github.com/xdslproject/xdsl/pull/423#discussion_r1103602231)). `Filecheck` failed to detect this on its own (even after trying the [`--match-full-lines`](https://filecheck.readthedocs.io/en/stable/06-options.html#match-full-lines) flag).

**Comment by webmiche** [comment]
Note: This is especially tough in the context of non guaranteed naming for ssavalues. We need to detect an arbitrary string there, that can be an SSAValue. Maybe, one could do something with the naming regex for SSAValues. Or one could try to "tag" the string and compare for equality where this SSAValues should be used again (though this is not supported by the current filecheck implementation, AFAIK).

**Comment by Moxinilian** [comment]
For reference, when writing the tests for MLIR IRDL, I did something like this:
```mlir
    // CHECK: irdl.type complex {
    // CHECK:   %[[v0:[^ ]*]] = irdl.is : f32 (!irdl.type_constr)
    // CHECK:   %[[v1:[^ ]*]] = irdl.is : f64 (!irdl.type_constr)
    // CHECK:   %[[v2:[^ ]*]] = irdl.any_of(%[[v0]], %[[v1]]) (!irdl.type_constr)
    // CHECK:   irdl.parameters(%[[v2]]) (!irdl.type_constr)
    // CHECK: }
    irdl.type complex {
      %0 = irdl.is : f32 (!irdl.type_constr)
      %1 = irdl.is : f64 (!irdl.type_constr)
      %2 = irdl.any_of(%0, %1) (!irdl.type_constr)
      irdl.parameters(%2) (!irdl.type_constr)
    }
```

**Comment by webmiche** [comment]
A workaround could also be to precompile and cache the LLVM FileCheck binaries...

**Comment by tobiasgrosser** [comment]
If there is a difference between Python Filecheck and LLVM's filecheck, we could also patch Python filecheck. Introducing a C++ compilation dependency on our tests seems an unfortunate choice, given that we do not have any C++ dependency at the moment.

**Comment by webmiche** [comment]
For reference, the github project can be found [here](https://github.com/mull-project/FileCheck.py).

**Comment by superlopuh** [comment]
Our new and improved filecheck can match on patterns like in the example Theo provided, closing
