### ISSUE TITLE
Add support for terminators

### ISSUE THREAD

**Issue by Dinistro** [xdslproject/xdsl#43]
I'm not sure if we really want terminators in xdsl, but they might be necessary for stronger verification passes. 
We do not enforce terminators in ChocoPy so far, which leads to issues while lowering.

**Comment by superlopuh** [comment]
The Toy dialect has the verification in `toy.func`, similar code could be added to `func`. Would likely want to handle more complex scenarios, reading the MLIR implementation is probably a good idea

**Comment by math-fehr** [comment]
This is now implemented.
