### ISSUE TITLE
Move to a common way of referring to an operation

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#462]
I have started to write 

```python
form xdsl.dialects import scf, func

# ...
  scf.For(..., [
    func.Call(...)
  ]
# ...
```

instead of 

```python
form xdsl.dialects.scf import For
from xdsl.dialects.func import Call

# ...
  For(..., [
    Call(...)
  ]
# ...
```

I find that this makes it much clearer which dialect an operation comes from. It's also closer to the printed version of things.

I think we should move towards using modules to namespace operations in our code.

Especially if we get more dialects in the future, when we will have clashes of class names

**Comment by superlopuh** [comment]
💯

**Comment by superlopuh** [comment]
I don't know if there's much to do in terms of issue, but I prefer this style as well

**Comment by webmiche** [comment]
continued [here](https://github.com/xdslproject/xdsl/discussions/463)
