### ISSUE TITLE
xDSL is happy to parse wrong operand types.

### ISSUE THREAD

**Issue by PapyChacal** [xdslproject/xdsl#472]
Currently, xDSL is happy to parse and verify:
```mlir
%dealloc_tok = "gpu.dealloc"(%func_tok, %memref) {"operand_segment_sizes" = array<i32: 1>} : (memref<3x3xindex>) -> !gpu.async.token
```
(See the operand types at the end: the number of operands do not match.)

Is this intended, or a bug? It is redundant in the textual format, but still should be recognized as incorrect IMO, be it in the parser or the verifier.

**Comment by math-fehr** [comment]
Yes, completely a bug, thanks for reporting it!

**Comment by PapyChacal** [comment]
Adding here for the record, it seems to be permissive with types too, not only number of arguments, as in:
```mlir
%sum = "arith.addi"(%lhs, %rhs) : (index, index) -> index
"gpu.yield"(%sum) : (f32) -> ()
```

**Comment by PapyChacal** [comment]
In case it helps, the type in the operation type (`() -> ()`) is ignored in favor of the type of the operand.
