### ISSUE TITLE
Highlighting and Arrows

### ISSUE THREAD

**Issue by moaylesbury** [xdslproject/xdsl#48]
On my thesis project I have many prints of a module as it is rewritten (see below), where the module is output with `printer.print_op(module)`. 

Following a meeting with Tobais and Mathieu, we think it would be incredible helpful if the printer could implement functionality for highlighting and arrows. Highlighting could simply be done by changing the output colour, and arrows could use a string such as "->". 

If anyone has any input on this, or any additional printer features they would like added, I would love to hear!

<img width="467" alt="image" src="https://user-images.githubusercontent.com/17080572/151707879-3c8ee060-f805-431c-830a-9b2924c85553.png">

Also, sorry if I have posted this in the wrong place.

**Comment by jpienaar** [comment]
When I did a UI before for an example, I found it easiest to utilize colab/ipython with markdown sections and https://github.com/highlightjs/highlightjs-mlir . Started with a dedicated extension there, but found custom cell magic later on to be more than sufficient. Ipython made it quite easy to inject other elements. Always the option of piping through chroma and getting SVG output too (note unfortunately the different syntax highlighters output may differ).

**Comment by superlopuh** [comment]
My understanding is that we're planning to migrate away from xdsl syntax, and the MLIR team supports a MLIR lsp with code highlighting. Please reopen if I've misunderstood the issue, and their syntax highlighting doesn't address the problem.
