### ISSUE TITLE
Refactor parsing and printing

### ISSUE THREAD

**Issue by math-fehr** [xdslproject/xdsl#5]
Currently, the parsing and printing is slightly broken.
First, raised by #3, we cannot print an operation/module to a string, but allowing to simply write `print(op)` would be nice.

However, this raises multiple issues:
* How to print an operation that refers to an external SSA value? Should we just give them a name like as `UNK0`, to show explicitely that the value is outside?
* Then, how to print a list of operation? If the second operation use a result of the first, we don't want to print an `UNK` for instance. I believe that in that case, we might have to use the `Printer` explicitly in some way.

**Comment by webmiche** [comment]
Is this now done by the new parser? Or should we just keep this open because we always want to refactor parsing/printing? @math-fehr

**Comment by math-fehr** [comment]
Yes, this is now much better, though we will continue on the parser itsilf.
But I guess we can close this ;)
