### ISSUE TITLE
Add a function to print filecheck lines given MLIR IR

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#534]
As a first step, should just print lines with `CHECK:` on first line, and `CHECK-NEXT:` on subsequent lines. Later, would be good to make the ssa names more flexible, so that their def-use chain is preserved but not the names, but not necessary for this task.

**Comment by webmiche** [comment]
The last part you mention might run into limitations of the filecheck python package. Check #428 for more info.

**Comment by superlopuh** [comment]
Ah nice, thank you! Then definitely worth deferring until we figure out whether we want to patch their code.

**Comment by superlopuh** [comment]
Implemented by @PapyChacal
