### ISSUE TITLE
Add `-split-input-file` option to xdsl-opt

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#554]
This should follow the `mlir-opt` format, as seen here:

https://github.com/llvm/llvm-project/blob/main/mlir/test/Dialect/PDL/ops.mlir

`mlir-opt -split-input-file -mlir-print-op-generic`

**Comment by AntonLydike** [comment]
How does `-split-input-file` work exactly? I don't really get it from the example...

**Comment by superlopuh** [comment]
It splits the file on 
```
// -----
```

And runs the command on the text in between. The advantage in time is that we don't need to start a new Python process each time, which is quite slow
