### ISSUE TITLE
Improve rewrite ergonomics

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#557]
During my implementations with the devito rewrites, I ran into a couple of things that could be improved with the rewrite system. Some of these are pretty trivial, others might require more involved solutions. Here they are in no particular order:

## [Done] Smarter `Operation.replace_operand`

Currently, `replace_operand` only takes the index of the operand to replace. I would like it to also take the old operand and let it figure out the index itseld. That would reduce the code from:

```py
op.replace_operand(
    op.operands.index(op.ub),
    new_ub.result
)
```
to 
```py
op.replace_operand(op.ub, new_ub.result)
```

## [Done] FuncOp Type Change

Rewriting the type of an argument of a `func.func` op is painful:

```py
for i, arg_typ in enumerate(op.function_type.inputs.data):
    if isinstance(arg_typ, iet_ssa.Dataobj):
        op.body.blocks[0].args[i].typ = llvm.LLVMPointerType.typed(
            iet_ssa.Dataobj.get_llvm_struct_type(), 
        )

op.attributes['function_type'] = builtin.FunctionType.from_lists(
    [arg.typ for arg in op.body.blocks[0].args],
    op.function_type.outputs.data,
)
```

Ideally there would be a better solution, maybe a method `FuncOp.regenereate_function_type()` that corrects the function type as per the block arguments and return values?

Or even a `FuncOp.change_arg_type(i | arg, new_type)` that updates the block argument and the function type attr?

## Support for moving operations?

I would like to easily move operations from one block to another, I'm not sure if there's an easy way to do that yet. (no code example yet, sorry)

## [Done] Allow negative values to `insert_op_at_pos`

I want to add operations at the end of blocks, this should be super straight forward.

```py
rewriter.insert_op_at_pos(scf.Yield(), new_body, len(new_body.ops))
```

becomes 
```py
rewriter.insert_op_at_pos(scf.Yield(), new_body, -1)
```

## Smarter Replace By

I want to go from:

```
%x = 1
someop(%x)
otherop(%x)
```

to 

```
%x = 1
%new_x = cast(x) to i32
%someop(%new_x)
%otherop(%new_x)
```

The problem is, that I can only call `SSAVal.replace_by` once I have a new SSA value. But the `replace_by` will *also* replace the use in my `cast` op. so I have to add it back:

```py
rewriter.insert_op_at_pos(
    new_x := arith.IndexCastOp.get(x, builtin.i32),
    block,
    0,
)
# replace all uses of `x` by `new_x`
loop_var.replace_by(new_x.result)
# re-add the use of `x` to the op that provides `new_x`
new_x.replace_operand(0, x)
```

I would like something like:

```py
rewriter.replace_ssa_val_by_result_of_ops(
  x, 
  [
    new_x := arith.IndexCastOp.get(loop_var, builtin.i32),
  ], 
  new_x.result
)
```

which would take care of correctly replacing the uses in all other ops.

**Comment by math-fehr** [comment]
Yes to all!
In particular I need to see how they deal with the last part in MLIR

**Comment by webmiche** [comment]
Thanks, these are all certainly useful suggestions. Just adding a stray thought I just had, if anyone tackles this in the future:
 
> ## FuncOp Type Change
> Rewriting the type of an argument of a `func.func` op is painful:
> 
> ```python
> for i, arg_typ in enumerate(op.function_type.inputs.data):
>     if isinstance(arg_typ, iet_ssa.Dataobj):
>         op.body.blocks[0].args[i].typ = llvm.LLVMPointerType.typed(
>             iet_ssa.Dataobj.get_llvm_struct_type(), 
>         )
> 
> op.attributes['function_type'] = builtin.FunctionType.from_lists(
>     [arg.typ for arg in op.body.blocks[0].args],
>     op.function_type.outputs.data,
> )
> ```
> 
> Ideally there would be a better solution, maybe a method `FuncOp.regenereate_function_type()` that corrects the function type as per the block arguments and return values?
> 
 IMO, this is a problem of the Op, not the rewriting. I agree that could have such an Op, but it should be part of the FuncOp class, IMO.

**Comment by AntonLydike** [comment]
I've just updated that part, I think a method on the `FuncOp` class like `FuncOp.change_arg_type(old: int | SSAValue, new_type: Attribute)`

**Comment by superlopuh** [comment]
@AntonLydike could you please split the remaining tasks into separate issues?

**Comment by AntonLydike** [comment]
Remaining tasks moved to #826
