### ISSUE TITLE
Misleading Error Messages when Constructing Operations Wrong

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#561]
Hey all, I have encountered this issue often enough to know what's the problem when I see this error message, but for beginners it's probably devastating:

```
>>> from xdsl.ir import Block
>>> from xdsl.dialects import arith
>>> cst = arith.Constant(1, 32)
>>> b = Block.from_ops([cst])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anton/uni/xdslproject/xdsl/xdsl/ir.py", line 799, in from_ops
    b.add_ops(ops)
  File "/home/anton/uni/xdslproject/xdsl/xdsl/ir.py", line 868, in add_ops
    self.add_op(op)
  File "/home/anton/uni/xdslproject/xdsl/xdsl/ir.py", line 859, in add_op
    self._attach_op(operation)
  File "/home/anton/uni/xdslproject/xdsl/xdsl/ir.py", line 845, in _attach_op
    raise ValueError(
ValueError: Can't add to a block an operation already attached to a block.
```

We should probably make sure that the `__init__` of an Operation fails when it is constructed in such a way. 

## Explanation for everyone who's confused by this:

 - We use an invalid mehtod of instantiation for the `arith.Constant` Operation (the constructor, lol). We should instead use some of the static methods attached to the class such as `from_int_and_width`.
 - Using the `__init__` method with the wrong arguments doesn't actually raise an error though. The first argument (`1`) will be assigned to the `.parent` attribute of the class though
 - When we try to attach the op to a Block, the `.parent` is not None, and therefore the code thinks we are adding something that is already added, when in fact we have erroneously constructed the operation.

**Comment by webmiche** [comment]
Hmm yeah that is nasty. I guess it comes from the dataclass decorator on operation...

This particular problem should be solved, once we actually move to using the init constructor for operations, but it is certainly good to keep track here :)

**Comment by webmiche** [comment]
As a quick fix, one could certainly add some verification to the post_init of Operation. At least that is what I would do :)

**Comment by AntonLydike** [comment]
I'm confused that the `dataclass` operator even allows assigning a `1` to something annotated `Block | None`...

**Comment by webmiche** [comment]
Welcome to Python!

I personally genuinely think there will be a moment where I will be annoyed enough by annotations not being enforced that I will hack into the python interpreter and give it an execution model that adds assertions on the types at the start of all functions with type hints. But that day is not today.

**Comment by webmiche** [comment]
> Welcome to Python!
> 
> I personally genuinely think there will be a moment where I will be annoyed enough by annotations not being enforced that I will hack into the python interpreter and change the executing AST or something such that it adds assertions on the types at the start of all functions with type hints. But that day is not today.

**Comment by AntonLydike** [comment]
Suggestion to solve this:

Add a `__post_init__` method to the `Operation` class that checks that the object was initialized correctly. This should be relatively straight forward, so I'm adding the good first issue label to this.

**Comment by superlopuh** [comment]
Since this issue was filed, we've broadly adopted adding custom inits to operations that prevent this sort of thing from happening, please reopen if you think it's still relevant
