### ISSUE TITLE
misc: lint irdl_mlir_printer.py

### ISSUE THREAD

**Issue by superlopuh** [xdslproject/xdsl#572]
PR #570 moves it to an `"ignore"` list in `pyproject.toml`, meaning that the errors won't be shown when navigating to it. We would like to get rid of the errors eventually.

**Comment by math-fehr** [comment]
I'm actually not sure this is worth the effort to be honest ^^'

**Comment by webmiche** [comment]
Well the impact might not be high, but the empty ignore list sure will feel good 😉

**Comment by superlopuh** [comment]
Neither am I :) But someone might still want to do it :) To be honest it would actually be good to have all files be linted, but I think it's safe in the ignore list for now

**Comment by superlopuh** [comment]
This file no longer exists
