### ISSUE TITLE
core: rename MLIRType

### ISSUE THREAD

**Issue by webmiche** [xdslproject/xdsl#607]
from [this comment](https://github.com/xdslproject/xdsl/pull/601#issuecomment-1483841242): It seems that the MLIRType is important for both parsing printing as well as for pdl, so we should make it part of xDSL itself more. To me, it seems that a simple rename to `Type` would already do a lot.

**Comment by webmiche** [comment]
Still doesn't work. I guess it makes most sense if you just start :+1:

**Comment by Fergtic** [comment]
Fair enough, sounds good

**Comment by Fergtic** [comment]
I think there should be a different name rather than ```Type``` as for example in ```xdsl/dialects/builtin.py``` we have the line (unless I'm misunderstanding something here lol):

```def __init__(self, constr: Attribute | Type[Attribute] | AttrConstraint):
        self.elem_constr = attr_constr_coercion(constr)
```
which causes conflictions with the newly defined ```Type```

**Comment by superlopuh** [comment]
you can spell that `type[Attribute]` But the conflict is not ideal, for other clients of the `xdsl` clients who might not want to do that for whatever reason

**Comment by Fergtic** [comment]
So maybe something like TypeAttr?

**Comment by webmiche** [comment]
TypeAttr isn't the way to go either, IMO. That already exists in MLIR and is used for something slightly different...

I guess it could be an xDSLType?

**Comment by AntonLydike** [comment]
Maybe `IsType`? It is supposed to be used like a mixin, so that name makes more sense in my head.

**Comment by Fergtic** [comment]
Would that be better than naming it ```IsType``` or something similar as we'll be using a different name in the file anyway if we use the import as feature? Might be better to keep the name consistent across files?

**Comment by Fergtic** [comment]
Ok!

**Comment by math-fehr** [comment]
I also like `TypeAttr`, though this has a different meaning in MLIR, so I'm not completely sure if this is the best name or not.
`Type` has the same problem, since people might use `typing.Type` and might confuse them.

I'm fine with both, I'm not feeling strongly to any of these!
