### ISSUE TITLE
Add pytest tests for the stencil dialect

### ISSUE THREAD

**Issue by meshtag** [xdslproject/xdsl#608]
It would be good to have tests for checking `get` methods and related infra for stencil dialect ops, this would also lead to easier rewriting as all involved functions will be thoroughly tested. This is a low priority task as of now and I am opening this issue to keep a track of it in future.

**Comment by Dovineowuor** [comment]
I am destined to working on this issue\

**Comment by superlopuh** [comment]
Let's just add tests as we iterate on the dialect
