### ISSUE TITLE
Region without a block is parsed as having a single empty block

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#740]
Noticed this with #727 

Basically, a region without a block is printed as `({})`, while a region with an empty block is printed as `({})`. 

The implementation must therefore "guess" if it should add an empty region or not. We currently assume it has, which is wrong in the case of `scf.if`.

**Comment by webmiche** [comment]
The two important factors here are MLIR's external functions (region with empty block) vs scf.if (region with no block)

**Comment by math-fehr** [comment]
Fixed by #971
