### ISSUE TITLE
Cleanup the Affine dialect

### ISSUE THREAD

**Issue by Dinistro** [xdslproject/xdsl#85]
The affine dialect still uses `new_op` instead of actual classes. Furthermore, it is nowhere near feature completion as IntegerSets are not yet supported. 
Either we change the existing operations to use IRDL or we drop the dialect completely. What do you think @math-fehr ?

**Comment by webmiche** [comment]
I saw some work in the linalg PR on it, so I feel that we should not drop it. I agree though that keeping zombie dialects around does not make a lot of sense, so I guess things that do not get updated should be removed probably.

**Comment by Dinistro** [comment]
The PR does not touch the existing operations, thus I suggest that we simply rewrite them to use IRDL.
