### ISSUE TITLE
`PatternRewriter` and `Rewriter` have different orders (and signatures) for `insert_op_after`

### ISSUE THREAD

**Issue by AntonLydike** [xdslproject/xdsl#859]
PatternRewriter:
```python
def insert_op_before(self, op: Operation | list[Operation], target_op: Operation):
```

Rewriter:
```python
def insert_op_before(op: Operation, new_op: Operation):
```

This means that `PatternRewriter.insert_op_before(new_op, target)` has reversed semantics to `Rewriter.insert_op_before(new_op, target)` (which will actually raise an exception, luckily enough).

Ideally we would get these APIs to agree to some extent...

**Comment by AntonLydike** [comment]
This holds both for `..._after` and `..._before`.

**Comment by superlopuh** [comment]
Good catch, thank you
