### ISSUE TITLE
MLIRConverter: fix for CF

### ISSUE THREAD

**Issue by Dinistro** [xdslproject/xdsl#90]
The MLIRConverter currently struggles with the CF dialect on some things related to operand_segment_sizes.

**Comment by webmiche** [comment]
Wasn't there something about successor blocks as well? Or was that resolved?

**Comment by Dinistro** [comment]
This is the CF problem I was referring to.

**Comment by Dinistro** [comment]
Some of the problems are related to a change in the multiple variadic operand handling: #91
