### ISSUE TITLE
Field shadowing and parametrized attributes (op.name/attr.name)

### ISSUE THREAD

**Issue by webmiche** [xdslproject/xdsl#98]
The following breaks with a `Exception 1 parameters expected, got 0`:

```
@irdl_attr_definition
class Foo(ParametrizedAttribute):
  name: str = "bar.foo"
  param = ParameterDef(AnyAttr())

# Try to construct
Foo([*SomeAttr*])
```

Removing the type annotation for the name field fixes it:

```
@irdl_attr_definition
class Foo(ParametrizedAttribute):
  name = "bar.foo"
  param = ParameterDef(AnyAttr())

# Try to construct
Foo([*SomeAttr*])
```

I think we should change the API s.t. names are not defined as fields. That would make it less error-prone. Maybe have the name of the Attribute as part of the decorator? `irdl_attr_definition("bar.foo")`

**Comment by math-fehr** [comment]
Yeah, you are probably right! Alternatively, we could just return an error whenever we have fields that are not definitions, or name

**Comment by superlopuh** [comment]
Update title for easier search
